apiVersion: v1
kind: Service
metadata:
  name: talos-workshop
  namespace: devopsdays-ams
spec:
  selector:
    app: talos-workshop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP