apiVersion: v1
kind: ConfigMap
metadata:
  name: talos-workshop-html
  namespace: devopsdays-ams
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Talos Workshop</title>
        <style>
            body {
                margin: 0;
                padding: 20px;
                font-family: Arial, sans-serif;
                background-color: #f5f5f5;
                display: flex;
                flex-direction: column;
                align-items: center;
            }
            .container {
                max-width: 90%;
                background: white;
                padding: 20px;
                border-radius: 8px;
                box-shadow: 0 2px 10px rgba(0,0,0,0.1);
                text-align: center;
            }
            img {
                max-width: 100%;
                height: auto;
                border-radius: 4px;
                margin: 20px 0;
            }
            h1 {
                color: #333;
                margin-bottom: 20px;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>Talos Workshop - DevOpsDays Amsterdam</h1>
            <iframe src="https://www.canva.com/design/DAGqHiNXSOg/76itLBjM2lBlEZU4eONNDg/view?embed" 
                    width="800" 
                    height="600" 
                    style="border: none; border-radius: 8px; margin: 20px 0;" 
                    allowfullscreen>
            </iframe>
        </div>
    </body>
    </html>

---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: talos-workshop
  namespace: devopsdays-ams
  labels:
    app: talos-workshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: talos-workshop
  template:
    metadata:
      labels:
        app: talos-workshop
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-content
          mountPath: /usr/share/nginx/html
          readOnly: true
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: html-content
        configMap:
          name: talos-workshop-html
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: talos-workshop-service
  namespace: devopsdays-ams
spec:
  selector:
    app: talos-workshop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort

# ---
# # ConfigMap for the certificate image (you'll need to create this from the file)