---
apiVersion: v1
kind: Namespace
metadata:
  name: talos-certificate
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: certificate-html
  namespace: talos-certificate
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Talos Workshop Certificate - DevOpsDays Amsterdam 2025</title>
        <style>
            * {
                margin: 0;
                padding: 0;
                box-sizing: border-box;
            }
            
            body {
                font-family: 'Arial', sans-serif;
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                min-height: 100vh;
                display: flex;
                justify-content: center;
                align-items: center;
                padding: 20px;
            }
            
            .certificate-container {
                background: white;
                border-radius: 15px;
                box-shadow: 0 20px 40px rgba(0,0,0,0.1);
                padding: 60px 80px;
                max-width: 800px;
                width: 100%;
                text-align: center;
                position: relative;
                border: 8px solid #2c3e50;
            }
            
            .certificate-container::before {
                content: '';
                position: absolute;
                top: 20px;
                left: 20px;
                right: 20px;
                bottom: 20px;
                border: 3px solid #3498db;
                border-radius: 8px;
            }
            
            .header {
                margin-bottom: 40px;
            }
            
            .title {
                font-size: 3em;
                color: #2c3e50;
                margin-bottom: 10px;
                font-weight: bold;
                text-shadow: 2px 2px 4px rgba(0,0,0,0.1);
            }
            
            .subtitle {
                font-size: 1.4em;
                color: #34495e;
                margin-bottom: 30px;
            }
            
            .content {
                margin: 40px 0;
                line-height: 1.8;
            }
            
            .recipient {
                font-size: 1.3em;
                color: #2c3e50;
                margin: 30px 0;
            }
            
            .achievement {
                font-size: 1.5em;
                color: #27ae60;
                font-weight: bold;
                margin: 30px 0;
                text-transform: uppercase;
                letter-spacing: 2px;
            }
            
            .details {
                font-size: 1.1em;
                color: #34495e;
                margin: 25px 0;
            }
            
            .signatures {
                display: flex;
                justify-content: space-around;
                margin-top: 60px;
                flex-wrap: wrap;
            }
            
            .signature {
                text-align: center;
                margin: 20px;
                flex: 1;
                min-width: 200px;
            }
            
            .signature-line {
                border-top: 2px solid #2c3e50;
                width: 200px;
                margin: 0 auto 10px;
            }
            
            .signature-name {
                font-weight: bold;
                color: #2c3e50;
                font-size: 1.1em;
            }
            
            .signature-title {
                color: #7f8c8d;
                font-size: 0.9em;
                margin-top: 5px;
            }
            
            .date {
                position: absolute;
                bottom: 30px;
                right: 50px;
                color: #7f8c8d;
                font-size: 1em;
            }
            
            .logo-section {
                display: flex;
                justify-content: space-between;
                align-items: center;
                margin-bottom: 30px;
                flex-wrap: wrap;
            }
            
            .logo {
                font-size: 1.2em;
                font-weight: bold;
                color: #3498db;
            }
            
            .talos-logo {
                font-size: 1.5em;
                color: #e74c3c;
                font-weight: bold;
            }
            
            .completion-status {
                background: linear-gradient(45deg, #27ae60, #2ecc71);
                color: white;
                padding: 15px 30px;
                border-radius: 50px;
                display: inline-block;
                margin: 20px 0;
                font-weight: bold;
                font-size: 1.2em;
                box-shadow: 0 5px 15px rgba(39, 174, 96, 0.3);
            }
            
            @media (max-width: 768px) {
                .certificate-container {
                    padding: 40px 30px;
                }
                
                .title {
                    font-size: 2.2em;
                }
                
                .signatures {
                    flex-direction: column;
                }
                
                .date {
                    position: static;
                    text-align: center;
                    margin-top: 30px;
                }
            }
        </style>
    </head>
    <body>
        <div class="certificate-container">
            <div class="logo-section">
                <div class="logo">TrueFullstaq</div>
                <div class="talos-logo">⚡ TALOS</div>
            </div>
            
            <div class="header">
                <h1 class="title">Certificate of Completion</h1>
                <p class="subtitle">Talos Workshop</p>
            </div>
            
            <div class="completion-status">
                ✅ WORKSHOP COMPLETED SUCCESSFULLY
            </div>
            
            <div class="content">
                <p class="recipient">This is to certify that</p>
                <h2 class="achievement">The Workshop Participant</h2>
                <p class="details">has successfully completed the <strong>Talos Kubernetes Workshop</strong></p>
                <p class="details">at <strong>DevOpsDays Amsterdam 2025</strong></p>
                <p class="details">demonstrating proficiency in:</p>
                <ul style="text-align: left; display: inline-block; margin: 20px 0;">
                    <li>Talos Linux cluster deployment</li>
                    <li>Kubernetes configuration management</li>
                    <li>Cluster bootstrapping and health monitoring</li>
                    <li>Talos and Kubernetes upgrades</li>
                    <li>Workload deployment and security policies</li>
                </ul>
            </div>
            
            <div class="signatures">
                <div class="signature">
                    <div class="signature-line"></div>
                    <div class="signature-name">Jorian Taks</div>
                    <div class="signature-title">Workshop Instructor<br>TrueFullstaq</div>
                </div>
                <div class="signature">
                    <div class="signature-line"></div>
                    <div class="signature-name">Erwin de Keijzer</div>
                    <div class="signature-title">Workshop Instructor<br>TrueFullstaq</div>
                </div>
            </div>
            
            <div class="date">
                DevOpsDays Amsterdam 2025
            </div>
        </div>
        
        <script>
            // Add some interactive elements
            document.addEventListener('DOMContentLoaded', function() {
                const certificate = document.querySelector('.certificate-container');
                
                // Add a subtle animation on load
                certificate.style.opacity = '0';
                certificate.style.transform = 'scale(0.9)';
                certificate.style.transition = 'all 0.5s ease-in-out';
                
                setTimeout(() => {
                    certificate.style.opacity = '1';
                    certificate.style.transform = 'scale(1)';
                }, 100);
                
                // Add print functionality
                document.addEventListener('keydown', function(e) {
                    if (e.ctrlKey && e.key === 'p') {
                        window.print();
                    }
                });
            });
        </script>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: talos-certificate
  namespace: talos-certificate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: talos-certificate
  template:
    metadata:
      labels:
        app: talos-certificate
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "16Mi"
            cpu: "10m"
          limits:
            memory: "32Mi"
            cpu: "50m"
        volumeMounts:
        - name: html-content
          mountPath: /usr/share/nginx/html
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 101
          runAsGroup: 101
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: html-content
        configMap:
          name: certificate-html
      securityContext:
        fsGroup: 101
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
---
apiVersion: v1
kind: Service
metadata:
  name: talos-certificate-service
  namespace: talos-certificate
spec:
  selector:
    app: talos-certificate
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
  type: NodePort